worker_processes 1;
daemon off;
error_log stderr notice;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 8080;
        lua_code_cache off;

        location / {
            default_type text/html;
            content_by_lua_block {
                require("lapis").serve("app")
            }
        }
    }
}
